#**TEXT AND WEB ANALYTICS**

##**LAB PRACTICAL 4**

###**MAHIMA MUNJAL** 

###**17CSU098**

**Q1. Demonstrate the computation of Similarity Metrics such as Jaccard, Levenshtein and Cosine.**

**JACCARD SIMILARITY**

In [17]:
#Jaccard Similarity - Method 1

def jaccard_similarity(list1, list2):
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection
    return float(intersection)/union

In [19]:
data1=input()
data2=input()
list1 = data1.split(" ")
list2 = data2.split(" ")
print("List 1 ",list1)
print("List 2 ",list2)

Mahima Munjal is a good girl
Mahima Munjal studies at NorthCap University
List 1  ['Mahima', 'Munjal', 'is', 'a', 'good', 'girl']
List 2  ['Mahima', 'Munjal', 'studies', 'at', 'NorthCap', 'University']


In [20]:
jaccard_similarity(list1, list2)

0.2

In [21]:
#Jaccard Similarity - Method 2

def jaccard_similarities(list1, list2):
    s1 = set(list1)
    s2 = set(list2)
    return float(len(s1.intersection(s2)) / len(s1.union(s2)))

In [22]:
jaccard_similarities(list1, list2)

0.2

In [24]:
#Jaccard Similarity -Method 3

import numpy as np
from sklearn.metrics import jaccard_score

jaccard_score([1,1,0,0],[0,1,0,1])

0.3333333333333333

In [11]:
pip install jaccard-index 

In [15]:
#Jaccard Index 

rom jaccard_index.jaccard import jaccard_index
jaccard_index("Mahima","Mahima Munjal")

0.5

**LEVENSHTEIN DISTANCE**



In [6]:
!apt install -qq enchant
!pip install pyenchant

The following additional packages will be installed:
  aspell aspell-en dictionaries-common emacsen-common hunspell-en-us
  libaspell15 libenchant1c2a libhunspell-1.6-0 libtext-iconv-perl
Suggested packages:
  aspell-doc spellutils wordlist hunspell openoffice.org-hunspell
  | openoffice.org-core libenchant-voikko
The following NEW packages will be installed:
  aspell aspell-en dictionaries-common emacsen-common enchant hunspell-en-us
  libaspell15 libenchant1c2a libhunspell-1.6-0 libtext-iconv-perl
0 upgraded, 10 newly installed, 0 to remove and 29 not upgraded.
Need to get 1,310 kB of archives.
After this operation, 5,353 kB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package libtext-iconv-perl.
(Reading database ... 160975 files and directories currently installed.)
Preparing to unpack .../0-libtext-iconv-perl_1.7-5build6_amd64.deb ...
Unpacking libtext-iconv-perl (1.7-5build6) ...
Selecting previously unselected package libaspe

**LEVENSHTEIN DISTANCE**



In [7]:
#Levenshtein Distance

import enchant

data1 = "Mahima Munjal is a good girl."
data2 = "Mahima Munjal"

enchant.utils.levenshtein(data1,data2)

16

**COSINE SIMILARITY**

In [8]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 

In [ ]:
I = input("Enter first string: ").lower() 
II = input("Enter second string: ").lower() 

Enter first string: Mahima Munjal is a good girl
Enter second string: Mahima Munjal studies at NCU and works at Nagarro


In [ ]:
# tokenization 
I_list = word_tokenize(I)  
II_list = word_tokenize(II) 
print('First List', I_list)
print('Second List', II_list)

First List ['mahima', 'munjal', 'is', 'a', 'good', 'girl']
Second List ['mahima', 'munjal', 'studies', 'at', 'ncu', 'and', 'works', 'at', 'nagarro']


In [ ]:
#removing stopwords

sw = stopwords.words('english')  
l1 =[];l2 =[] 
I_set = {w for w in I_list if not w in sw}  
II_set = {w for w in II_list if not w in sw} 
print('First Set', I_set)
print('Second Set', II_set)

First Set {'good', 'mahima', 'girl', 'munjal'}
Second Set {'nagarro', 'ncu', 'studies', 'munjal', 'works', 'mahima'}


In [ ]:
# Forming a set containing keywords of both strings 

rvector = I_set.union(II_set)  
for w in rvector: 
    if w in I_set: l1.append(1) 
    else: l1.append(0) 
    if w in II_set: l2.append(1) 
    else: l2.append(0) 
c = 0

In [ ]:
# cosine formula  
for i in range(len(rvector)): 
        c+= l1[i]*l2[i] 
cosine = c / float((sum(l1)*sum(l2))**0.5) 

print('Cosine Similarity Value :',cosine)

Cosine Similarity Value : 0.4082482904638631


**COSINE SIMILARITY MATRIX**

In [ ]:
I = input("Enter first string: ").lower() 
II = input("Enter second string: ").lower() 

Enter first string: Mahima Munjal is a student of Text and Web Analytics
Enter second string: Mahima Munjal is a student of The Northcap University


In [ ]:
documents = [I,II]

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [ ]:
count_vectorizer = CountVectorizer(stop_words='english')
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(documents)


doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index=['I', 'II'])
df

analytics  and  is  mahima  munjal  ...  student  text  the  university  web
I           1    1   1       1       1  ...        1     1    0           0    1
II          0    0   1       1       1  ...        1     0    1           1    0

[2 rows x 12 columns]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df, df))

[[1.         0.58925565]
 [0.58925565 1.        ]]


**Q2. CALCULATE THE TFIDF VECTORIZOR ON 2 DOCUMENTS.**

In [25]:
I = input("Enter first string: ").lower() 
II = input("Enter second string: ").lower() 

Enter first string: Mahima Munjal loves to watch movies
Enter second string: Mahima Munjal loves to do yoga


In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [I,II]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print('Vectorizer Features :',vectorizer.get_feature_names())
print('Vectorizer Shape: ',X.shape)

Vectorizer Features : ['do', 'loves', 'mahima', 'movies', 'munjal', 'to', 'watch', 'yoga']
Vectorizer Shape:  (2, 8)


In [28]:
print("TF-IDF Scores")
print(X)

TF-IDF Scores
  (0, 3)	0.49844627974580596
  (0, 6)	0.49844627974580596
  (0, 5)	0.35464863330313684
  (0, 1)	0.35464863330313684
  (0, 4)	0.35464863330313684
  (0, 2)	0.35464863330313684
  (1, 7)	0.49844627974580596
  (1, 0)	0.49844627974580596
  (1, 5)	0.35464863330313684
  (1, 1)	0.35464863330313684
  (1, 4)	0.35464863330313684
  (1, 2)	0.35464863330313684


**Q3. Apply the max-df, min-df param in the TF-IDF function.**

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
data = [I,II]
count_vec = CountVectorizer(stop_words="english", analyzer='word',ngram_range=(1, 1), max_df=0.50, min_df=1, max_features=None)

count_train = count_vec.fit(data)
bag_of_words = count_vec.transform(data)

print('Features :',count_vec.get_feature_names())

Features : ['movies', 'watch', 'yoga']


In [36]:
print("Count Vectorizer Scores")
print(bag_of_words)

Count Vectorizer Scores
  (0, 0)	1
  (0, 1)	1
  (1, 2)	1


**Q4. Compute Cosine Similarity using both TF-IDF and Count vectorizer.**

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk.corpus import stopwords
import numpy as np
import numpy.linalg as LA
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
train_set = ["Mahima Munjal is a good girl", "Mahima Munjal studies at The Northcap University."]    # Documents
test_set = ["A good girl named Mahima Munjal studies at the Northcap University."]    # Query
stopWords = stopwords.words('english')

In [ ]:
vectorizer = CountVectorizer(stop_words = stopWords)
print('Vectorizer : ',vectorizer)
transformer = TfidfTransformer()
print('\n\nTF-IDF Transformer : ',transformer)

Vectorizer :  CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


TF-IDF Transformer :  TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)


In [ ]:
#Using Count Vectorizer

trainVectorizerArray = vectorizer.fit_transform(train_set).toarray()
testVectorizerArray = vectorizer.transform(test_set).toarray()
print ('Fit Vectorizer to train set \n', trainVectorizerArray)
print ('\n\nTransform Vectorizer to test set\n', testVectorizerArray)

Fit Vectorizer to train set 
 [[1 1 1 1 0 0 0]
 [0 0 1 1 1 1 1]]


Transform Vectorizer to test set
 [[1 1 1 1 1 1 1]]


In [ ]:
#Using TF-IDF

transformer.fit(trainVectorizerArray)
print('Fit transformer to train set \n',transformer.transform(trainVectorizerArray).toarray())
transformer.fit(testVectorizerArray)
tfidf = transformer.transform(testVectorizerArray)
print('\n\nFit transformer to test set\n',tfidf.todense())

Fit transformer to train set 
 [[0.57615236 0.57615236 0.40993715 0.40993715 0.         0.
  0.        ]
 [0.         0.         0.35520009 0.35520009 0.49922133 0.49922133
  0.49922133]]


Fit transformer to test set
 [[0.37796447 0.37796447 0.37796447 0.37796447 0.37796447 0.37796447
  0.37796447]]


**Q5. Find the words in the vocabulary with the highest TF-IDF score.**

In [ ]:
I = input("Enter first string: ").lower() 
II = input("Enter second string: ").lower() 

Enter first string: Katrina Kaif is the best actress. She is the most versatile actress of current genration. She loves to be the best. She is very sincere and hardworking.
Enter second string: Indira Gandhi is the best prime minister till date, She is an epitome of grace, power, intellect and bravery. She is my idol. She was the best in each task she did.


In [ ]:
import math
from textblob import TextBlob as tb

In [ ]:
def tf(word, computation):
    return computation.words.count(word) / len(computation.words)

def n_containing(word, mylist):
    return sum(1 for computation in mylist if word in computation.words)

def idf(word, mylist):
    return math.log(len(mylist) / (1 + n_containing(word, mylist)))

def tfidf(word, computation, mylist):
    return tf(word, computation) * idf(word, mylist)

In [ ]:
I=tb(I)
II=tb(II)
mylist = [I,II]
for i, computation in enumerate(mylist):
    print("\nTop words in document {}".format(i + 1))
    scores = {word: tfidf(word, computation, mylist) for word in computation.words}
    sorted_words = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    for word, score in sorted_words[:3]:
        print("\tWord: {}, TF-IDF: {}".format(word, round(score, 5)))

Top words in document 1
	Word: katrina, TF-IDF: 0.0
	Word: kaif, TF-IDF: 0.0
	Word: actress, TF-IDF: 0.0
Top words in document 2
	Word: indira, TF-IDF: 0.0
	Word: gandhi, TF-IDF: 0.0
	Word: prime, TF-IDF: 0.0
