#**TEXT AND WEB ANALYTICS**

##**LAB PRACTICAL 7**

###**MAHIMA MUNJAL** 

###**17CSU098**

In [ ]:
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline


In [ ]:
categories = ['rec.motorcycles', 'sci.electronics',
              'comp.graphics', 'sci.med']


train_data = fetch_20newsgroups(subset='train',
                                categories=categories, shuffle=True, random_state=42)

print(train_data.target_names)

print("\n".join(train_data.data[0].split("\n")[:3]))
print(train_data.target_names[train_data.target[0]])


for t in train_data.target[:10]:
    print(train_data.target_names[t])



['comp.graphics', 'rec.motorcycles', 'sci.electronics', 'sci.med']
From: kreyling@lds.loral.com (Ed Kreyling 6966)
Subject: Sun-os and 8bit ASCII graphics
Organization: Loral Data Systems
comp.graphics
comp.graphics
comp.graphics
rec.motorcycles
comp.graphics
sci.med
sci.electronics
sci.electronics
comp.graphics
rec.motorcycles
sci.electronics


### **COUNT VECTORIZER AND TFIDF VECTORIZER**

In [ ]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(train_data.data)

tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)


## **K-Nearest Neighbour**

In [ ]:
knn = KNeighborsClassifier(n_neighbors=7)

# training our classifier ; train_data.target will be having numbers assigned for each category in train data
clf = knn.fit(X_train_tfidf, train_data.target)

# Input Data to predict their classes of the given categories
docs_new = ['I want to buy a computer.', 'I have a television at my home.']

X_new_counts = count_vect.transform(docs_new)
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

In [ ]:
# predicting the category of our input text: Will give out number for category
predicted = clf.predict(X_new_tfidf)

for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, train_data.target_names[category]))


    

'I want to buy a computer.' => sci.electronics
'I have a television at my home.' => comp.graphics


In [ ]:
text_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', knn),
])

# Fitting our train data to the pipeline
text_clf.fit(train_data.data, train_data.target)

# Test data 
test_data = fetch_20newsgroups(subset='test',
                               categories=categories, shuffle=True, random_state=42)
docs_test = test_data.data
# Predicting our test data
predicted = text_clf.predict(docs_test)
print('Accuracy :',np.mean(predicted == test_data.target)*100,'%')


Accuracy : 82.67766497461929 %


## **Naive bayes**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_train_tfidf, train_data.target, test_size=0.30, random_state=42)

print('Training Data Shape:', X_train.shape)
print('Testing Data Shape: ', X_test.shape)

Training Data Shape: (1656, 35653)
Testing Data Shape:  (711, 35653)


In [ ]:
y1=X_train.todense()
y1

matrix([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.00508825, 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
lr_model = GaussianNB()
lr_model.fit(y1, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y2=X_test.todense()
y2

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
predictions = lr_model.predict(y2)
predictions

array([2, 0, 2, 1, 2, 3, 0, 1, 1, 3, 3, 2, 3, 1, 3, 3, 2, 0, 0, 3, 0, 3,
       0, 2, 3, 1, 2, 1, 0, 0, 3, 3, 1, 1, 3, 2, 0, 0, 3, 3, 1, 1, 0, 3,
       0, 1, 3, 0, 1, 3, 3, 0, 2, 0, 3, 3, 3, 0, 3, 1, 1, 1, 2, 0, 2, 2,
       3, 2, 1, 1, 2, 0, 0, 0, 2, 2, 0, 3, 2, 1, 2, 2, 1, 3, 3, 3, 3, 1,
       1, 0, 3, 1, 1, 1, 3, 1, 0, 1, 3, 0, 3, 1, 0, 0, 0, 0, 3, 1, 0, 1,
       2, 0, 3, 1, 2, 0, 1, 3, 1, 0, 1, 1, 2, 0, 3, 0, 3, 3, 1, 0, 1, 2,
       3, 1, 3, 2, 2, 1, 2, 3, 0, 1, 1, 0, 2, 0, 1, 3, 3, 3, 0, 1, 1, 1,
       2, 1, 1, 0, 1, 3, 0, 2, 2, 2, 0, 1, 3, 1, 2, 1, 1, 2, 1, 2, 3, 3,
       1, 3, 2, 0, 1, 1, 2, 1, 3, 3, 0, 2, 3, 2, 2, 1, 0, 3, 3, 1, 3, 1,
       1, 0, 0, 3, 2, 3, 1, 0, 0, 0, 0, 0, 0, 3, 2, 3, 1, 3, 2, 2, 3, 1,
       2, 1, 0, 1, 3, 0, 1, 0, 3, 2, 1, 0, 2, 1, 3, 1, 1, 0, 0, 2, 3, 3,
       2, 0, 1, 1, 1, 1, 0, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 0, 1, 1, 0, 3,
       1, 0, 0, 2, 3, 0, 2, 3, 0, 1, 2, 0, 0, 1, 3, 0, 3, 1, 2, 2, 2, 1,
       0, 0, 3, 2, 3, 0, 2, 0, 0, 3, 3, 0, 0, 3, 3,

### CONFUSION MATRIX

In [ ]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[150   1   9   7]
 [  4 177   3   5]
 [ 18   4 144   6]
 [  1   2   8 172]]


### CLASSIFICATION SUMMARY

In [ ]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       167
           1       0.97      0.99      0.98       189
           2       0.95      0.95      0.95       172
           3       0.98      0.96      0.97       183

    accuracy                           0.97       711
   macro avg       0.97      0.97      0.97       711
weighted avg       0.97      0.97      0.97       711



In [ ]:
print('Accuracy :',metrics.accuracy_score(y_test,predictions)*100,'%')

Accuracy : 90.43600562587905 %


## **Multinomial Naive Bayes**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_train_tfidf, train_data.target, test_size=0.30, random_state=42)

print('Training Data Shape:', X_train.shape)
print('Testing Data Shape: ', X_test.shape)

Training Data Shape: (1656, 35653)
Testing Data Shape:  (711, 35653)


In [ ]:
from sklearn.naive_bayes import MultinomialNB
lr_model = MultinomialNB()
lr_model.fit(X_train, y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
predictions = lr_model.predict(X_test)
predictions

array([2, 2, 2, 1, 2, 3, 0, 1, 1, 3, 3, 2, 3, 1, 3, 3, 2, 0, 0, 3, 0, 1,
       0, 2, 3, 1, 3, 1, 0, 0, 3, 3, 1, 1, 3, 2, 0, 0, 3, 3, 1, 1, 2, 3,
       0, 1, 3, 0, 1, 3, 3, 0, 2, 0, 1, 3, 3, 0, 3, 1, 1, 1, 2, 0, 2, 3,
       2, 2, 1, 1, 2, 0, 0, 0, 2, 2, 0, 3, 2, 1, 2, 2, 1, 3, 3, 3, 1, 1,
       1, 0, 3, 1, 1, 1, 3, 1, 0, 1, 3, 0, 3, 2, 0, 0, 0, 0, 3, 1, 0, 1,
       2, 0, 3, 1, 2, 2, 1, 3, 1, 0, 1, 1, 2, 0, 3, 3, 1, 3, 1, 0, 1, 2,
       3, 1, 3, 2, 3, 1, 2, 3, 0, 1, 1, 0, 2, 0, 3, 2, 3, 3, 2, 1, 1, 1,
       2, 1, 1, 0, 1, 3, 0, 2, 2, 2, 0, 1, 3, 1, 2, 1, 1, 2, 1, 2, 3, 3,
       1, 3, 2, 0, 1, 1, 2, 1, 0, 3, 0, 2, 3, 2, 2, 1, 0, 3, 0, 1, 3, 1,
       1, 2, 3, 3, 2, 3, 1, 0, 0, 0, 0, 2, 0, 3, 2, 3, 1, 3, 2, 2, 3, 1,
       2, 1, 0, 1, 3, 0, 1, 0, 3, 2, 1, 0, 1, 1, 3, 1, 1, 0, 0, 2, 3, 3,
       2, 0, 0, 1, 1, 1, 0, 1, 1, 2, 2, 3, 3, 3, 3, 1, 1, 0, 1, 1, 0, 3,
       1, 0, 0, 2, 3, 0, 2, 3, 0, 1, 2, 0, 0, 1, 3, 0, 3, 1, 2, 2, 2, 1,
       2, 0, 3, 2, 3, 0, 2, 0, 0, 3, 1, 0, 0, 1, 3,

### CONFUSION MATRIX

In [ ]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[161   0   4   2]
 [  0 187   1   1]
 [  5   3 164   0]
 [  3   2   3 175]]


### CLASSIFICATION SUMMARY

In [ ]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       167
           1       0.97      0.99      0.98       189
           2       0.95      0.95      0.95       172
           3       0.98      0.96      0.97       183

    accuracy                           0.97       711
   macro avg       0.97      0.97      0.97       711
weighted avg       0.97      0.97      0.97       711



In [ ]:
print("Accuracy:  ",metrics.accuracy_score(y_test,predictions)*100,'%')

Accuracy:   96.62447257383965 %
